name: Generate HTML Pages and Deploy to Repository for Preview

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Clean the priv directory
        run: |
          rm -rf priv/* # Limpa o diretório 'priv'

      - name: Create priv directory and index.html (Main page)
        run: |
          mkdir -p priv
          echo '<!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Main Page</title>
          </head>
          <body>
              <h1>Main Page</h1>
              <p>This is the main page of the GitHub Actions-generated HTML.</p>
              <a href="page1/index.html">Go to Page 1</a><br>
              <a href="page2/index.html">Go to Page 2</a><br>
              <a href="page3/index.html">Go to Page 3</a>
          </body>
          </html>' > priv/index.html

      - name: Create page1/index.html
        run: |
          mkdir -p priv/page1
          echo '<!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Page 1</title>
          </head>
          <body>
              <h1>Page 1</h1>
              <p>This is Page 1.</p>
              <a href="../index.html">Back to Main Page</a><br>
              <a href="../page2/index.html">Go to Page 2</a><br>
              <a href="../page3/index.html">Go to Page 3</a>
          </body>
          </html>' > priv/page1/index.html

      - name: Create page2/index.html
        run: |
          mkdir -p priv/page2
          echo '<!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Page 2</title>
          </head>
          <body>
              <h1>Page 2</h1>
              <p>This is Page 2.</p>
              <a href="../index.html">Back to Main Page</a><br>
              <a href="../page1/index.html">Go to Page 1</a><br>
              <a href="../page3/index.html">Go to Page 3</a>
          </body>
          </html>' > priv/page2/index.html

      - name: Create page3/index.html
        run: |
          mkdir -p priv/page3
          echo '<!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Page 3</title>
          </head>
          <body>
              <h1>Page 3</h1>
              <p>This is Page 3.</p>
              <a href="../index.html">Back to Main Page</a><br>
              <a href="../page1/index.html">Go to Page 1</a><br>
              <a href="../page2/index.html">Go to Page 2</a>
          </body>
          </html>' > priv/page3/index.html

      - name: Commit and push HTML files to branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add priv/
          git diff --cached --exit-code || git commit -m "Generate and update HTML pages"
          git push origin main --force

  display-summary:
    needs: generate-pages
    runs-on: ubuntu-latest
    steps:
      - name: Display preview links
        run: |
          echo "## HTML Pages Preview" >> $GITHUB_STEP_SUMMARY
          echo "The following pages are available for preview:" >> $GITHUB_STEP_SUMMARY
          echo "- [Main Page](https://github.com/${{ github.repository }}/blob/main/priv/index.html)" >> $GITHUB_STEP_SUMMARY
          echo "- [Page 1](https://github.com/${{ github.repository }}/blob/main/priv/page1/index.html)" >> $GITHUB_STEP_SUMMARY
          echo "- [Page 2](https://github.com/${{ github.repository }}/blob/main/priv/page2/index.html)" >> $GITHUB_STEP_SUMMARY
          echo "- [Page 3](https://github.com/${{ github.repository }}/blob/main/priv/page3/index.html)" >> $GITHUB_STEP_SUMMARY
