name: Generate HTML Pages and Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Clean the docs directory
        run: |
          rm -rf docs/* # Limpa o diretório 'docs' antes de adicionar os novos arquivos HTQML

      - name: Create docs directory and index.html (Main page)
        run: |
          mkdir -p docs
          echo '<!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Main Page</title>
          </head>
          <body>
              <h1>Main Page</h1>
              <p>This is the main page of the GitHub Pages website.</p>
              <a href="page1/index.html">Go to Page 1</a><br>
              <a href="page2/index.html">Go to Page 2</a><br>
              <a href="page3/index.html">Go to Page 3</a>
          </body>
          </html>' > docs/index.html

      - name: Create page1/teste.html
        run: |
          mkdir -p docs/page1
          echo '<!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Page 1111111212121212</title>
          </head>
          <body>
              <h1>Page 345</h1>
              <p>This is Test 12345 Page 5.</p>
              <a href="../index.html">Back to Main Page</a><br>
              <a href="page2/index.html">Go to Page 2</a><br>
              <a href="page3/index.html">Go to Page 3</a>
          </body>
          </html>' > docs/page1/index.html

      - name: Create page2/index.html
        run: |
          mkdir -p docs/page2
          echo '<!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Page 2</title>
          </head>
          <body>
              <h1>Page 2</h1>
              <p>This is Page 2.</p>
              <a href="../index.html">Back to Main Page</a><br>
              <a href="page1/index.html">Go to Page 1</a><br>
              <a href="page3/index.html">Go to Page 3</a>
          </body>
          </html>' > docs/page2/index.html

      - name: Create page3/index.html
        run: |
          mkdir -p docs/page3
          echo '<!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Page 3</title>
          </head>
          <body>
              <h1>Page 3</h1>
              <p>This is Page 3.</p>
              <a href="../index.html">Back to Main Page</a><br>
              <a href="page1/index.html">Go to Page 1</a><br>
              <a href="page2/index.html">Go to Page 2</a>
          </body>
          </html>' > docs/page3/index.html

      - name: Upload generated HTML files as artifact
        uses: actions/upload-artifact@v3
        with:
          name: html-pages
          path: docs/

  deploy-pages:
    needs: generate-pages
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Download generated HTML pages artifact
        uses: actions/download-artifact@v3
        with:
          name: html-pages
          path: docs/

      - name: Set up Git configuration for push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Commit and push changes to main branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add docs/
          git diff --cached --exit-code || git commit -m "Deploy HTML pages to docs folder"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} main --force

  display-summary:
    needs: deploy-pages
    runs-on: ubuntu-latest
    steps:
      - name: Display link to pages
        run: |
          USERNAME=${{ github.actor }}  # Variável para o nome de usuário
          REPOSITORY=${{ github.repository }}  # Variável para o nome do repositório
          
          echo "## HTML Pages Deployed to GitHub Pages" >> $GITHUB_STEP_SUMMARY
          echo "You can view the pages by clicking the links below:" >> $GITHUB_STEP_SUMMARY
          echo "Main page: [Preview Main Page](https://$USERNAME.github.io/$REPOSITORY/index.html)" >> $GITHUB_STEP_SUMMARY
          echo "Page 1: [Preview Page 1](https://$USERNAME.github.io/$REPOSITORY/page1/index.html)" >> $GITHUB_STEP_SUMMARY
          echo "Page 2: [Preview Page 2](https://$USERNAME.github.io/$REPOSITORY/page2/index.html)" >> $GITHUB_STEP_SUMMARY
          echo "Page 3: [Preview Page 3](https://$USERNAME.github.io/$REPOSITORY/page3/index.html)" >> $GITHUB_STEP_SUMMARY




