name: Generate HTML Pages and Publish to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Clean the priv directory
        run: |
          rm -rf priv/* # Limpa o diretório 'priv' antes de adicionar os novos arquivos HTML

      - name: Create priv directory and index.html (Main page)
        run: |
          mkdir -p priv
          echo '<!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Main Page</title>
          </head>
          <body>
              <h1>Main Page</h1>
              <p>This is the main page of the GitHub Pages website.</p>
              <a href="page1/index.html">Go to Page 1</a><br>
              <a href="page2/index.html">Go to Page 2</a><br>
              <a href="page3/index.html">Go to Page 3</a>
          </body>
          </html>' > priv/index.html

      - name: Create page1/index.html
        run: |
          mkdir -p priv/page1
          echo '<!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Page 1</title>
          </head>
          <body>
              <h1>Page 1</h1>
              <p>This is Page 1.</p>
              <a href="../index.html">Back to Main Page</a><br>
              <a href="../page2/index.html">Go to Page 2</a><br>
              <a href="../page3/index.html">Go to Page 3</a>
          </body>
          </html>' > priv/page1/index.html

      - name: Create page2/index.html
        run: |
          mkdir -p priv/page2
          echo '<!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Page 2</title>
          </head>
          <body>
              <h1>Page 2</h1>
              <p>This is Page 2.</p>
              <a href="../index.html">Back to Main Page</a><br>
              <a href="../page1/index.html">Go to Page 1</a><br>
              <a href="../page3/index.html">Go to Page 3</a>
          </body>
          </html>' > priv/page2/index.html

      - name: Create page3/index.html
        run: |
          mkdir -p priv/page3
          echo '<!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Page 3</title>
          </head>
          <body>
              <h1>Page 3</h1>
              <p>This is Page 3.</p>
              <a href="../index.html">Back to Main Page</a><br>
              <a href="../page1/index.html">Go to Page 1</a><br>
              <a href="../page2/index.html">Go to Page 2</a>
          </body>
          </html>' > priv/page3/index.html

      - name: Check for changes and commit if necessary
        run: |
          git status # Verifica o status para garantir que há alterações
          git add priv/ # Adiciona as alterações
          git diff --cached --exit-code || git commit -m "Generate HTML files in priv/" # Realiza o commit apenas se houver mudanças
          git push origin main # Empurra as alterações para a branch main

  display-summary:
    needs: generate-pages
    runs-on: ubuntu-latest
    steps:
      - name: Display link to pages
        run: |
          USERNAME=${{ github.actor }}
          REPO_NAME=${{ github.repository }}
          
          # Display links in the step summary
          echo "## HTML Pages Deployed to GitHub Pages" >> $GITHUB_STEP_SUMMARY
          echo "You can view the pages by clicking the links below:" >> $GITHUB_STEP_SUMMARY
          echo "Main page: [Preview Main Page](https://$USERNAME.github.io/$REPO_NAME/priv/index.html)" >> $GITHUB_STEP_SUMMARY
          echo "Page 1: [Preview Page 1](https://$USERNAME.github.io/$REPO_NAME/priv/page1/index.html)" >> $GITHUB_STEP_SUMMARY
          echo "Page 2: [Preview Page 2](https://$USERNAME.github.io/$REPO_NAME/priv/page2/index.html)" >> $GITHUB_STEP_SUMMARY
          echo "Page 3: [Preview Page 3](https://$USERNAME.github.io/$REPO_NAME/priv/page3/index.html)" >> $GITHUB_STEP_SUMMARY
