name: Generate HTML Pages and Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Create index.html (Main page)
        run: |
          echo '<!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Main Page</title>
          </head>
          <body>
              <h1>Main Page</h1>
              <p>This is the main page of the GitHub Pages website.</p>
              <a href="page1/index.html">Go to Page 1</a><br>
              <a href="page2/index.html">Go to Page 2</a><br>
              <a href="page3/index.html">Go to Page 3</a>
          </body>
          </html>' > index.html

      - name: Create page1/index.html
        run: |
          mkdir -p page1
          echo '<!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Page 1</title>
          </head>
          <body>
              <h1>Page 1</h1>
              <p>This is Page 1.</p>
              <a href="../index.html">Back to Main Page</a><br>
              <a href="page2/index.html">Go to Page 2</a><br>
              <a href="page3/index.html">Go to Page 3</a>
          </body>
          </html>' > page1/index.html

      - name: Create page2/index.html
        run: |
          mkdir -p page2
          echo '<!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Page 2</title>
          </head>
          <body>
              <h1>Page 2</h1>
              <p>This is Page 2.</p>
              <a href="../index.html">Back to Main Page</a><br>
              <a href="page1/index.html">Go to Page 1</a><br>
              <a href="page3/index.html">Go to Page 3</a>
          </body>
          </html>' > page2/index.html

      - name: Create page3/index.html
        run: |
          mkdir -p page3
          echo '<!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Page 3</title>
          </head>
          <body>
              <h1>Page 3</h1>
              <p>This is Page 3.</p>
              <a href="../index.html">Back to Main Page</a><br>
              <a href="page1/index.html">Go to Page 1</a><br>
              <a href="page2/index.html">Go to Page 2</a>
          </body>
          </html>' > page3/index.html

      - name: Verify file existence (for debugging)
        run: |
          echo "Verifying if the files are created"
          ls -alh # Verifique se os arquivos foram criados

  deploy-pages:
    needs: generate-pages
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Git configuration for push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Commit and push changes to main branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add .
          git commit -m "Deploy HTML pages to main branch" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} main --force

  display-summary:
    needs: deploy-pages
    runs-on: ubuntu-latest
    steps:
      - name: Display link to pages
        run: |
          echo "## HTML Pages Deployed to GitHub Pages" >> $GITHUB_STEP_SUMMARY
          echo "You can view the pages by clicking the links below:" >> $GITHUB_STEP_SUMMARY
          echo "Main page: [Preview Main Page](https://<usuario>.github.io/<repositorio>/index.html)" >> $GITHUB_STEP_SUMMARY
          echo "Page 1: [Preview Page 1](https://<usuario>.github.io/<repositorio>/page1/index.html)" >> $GITHUB_STEP_SUMMARY
          echo "Page 2: [Preview Page 2](https://<usuario>.github.io/<repositorio>/page2/index.html)" >> $GITHUB_STEP_SUMMARY
          echo "Page 3: [Preview Page 3](https://<usuario>.github.io/<repositorio>/page3/index.html)" >> $GITHUB_STEP_SUMMARY
           echo "" >> $GITHUB_STEP_SUMMARY
          echo "Main page: [Preview Main Page](https://raw.githack.com/${{ github.repository }}/pg-pages/index.html)" >> $GITHUB_STEP_SUMMARY
          echo "Page 1: [Preview Page 1](https://raw.githack.com/${{ github.repository }}/pg-pages/page1/index.html)" >> $GITHUB_STEP_SUMMARY
          echo "Page 2: [Preview Page 2](https://raw.githack.com/${{ github.repository }}/pg-pages/page2/index.html)" >> $GITHUB_STEP_SUMMARY
          echo "Page 3: [Preview Page 3](https://raw.githack.com/${{ github.repository }}/pg-pages/page3/index.html)" >> $GITHUB_STEP_SUMMARY
