name: Generate HTML Pages and Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Clean the public directory
        run: |
          rm -rf public/* # Limpa o diretório 'public' antes de adicionar os novos arquivos HTQML

      - name: Create public directory and index.html (Main page)
        run: |
          mkdir -p public
          echo '<!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Main Page</title>
          </head>
          <body>
              <h1>Main Page</h1>
              <p>This is the main page of the GitHub Pages website.</p>
              <a href="page1/index.html">Go to Page 1</a><br>
              <a href="page2/index.html">Go to Page 2</a><br>
              <a href="page3/index.html">Go to Page 3</a>
          </body>
          </html>' > public/index.html

      - name: Create page1/index.html
        run: |
          mkdir -p public/page1
          echo '<!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Page 1</title>
          </head>
          <body>
              <h1>Page 1</h1>
              <p>This is Test 12345 Page 5.</p>
              <a href="../index.html">Back to Main Page</a><br>
              <a href="page2/index.html">Go to Page 2</a><br>
              <a href="page3/index.html">Go to Page 3</a>
          </body>
          </html>' > public/page1/index.html

      - name: Create page2/index.html
        run: |
          mkdir -p public/page2
          echo '<!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Page 2</title>
          </head>
          <body>
              <h1>Page 2</h1>
              <p>This is Page 2.</p>
              <a href="../index.html">Back to Main Page</a><br>
              <a href="page1/index.html">Go to Page 1</a><br>
              <a href="page3/index.html">Go to Page 3</a>
          </body>
          </html>' > public/page2/index.html

      - name: Create page3/index.html
        run: |
          mkdir -p public/page3
          echo '<!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Page 3</title>
          </head>
          <body>
              <h1>Page 3</h1>
              <p>This is Page 3.</p>
              <a href="../index.html">Back to Main Page</a><br>
              <a href="page1/index.html">Go to Page 1</a><br>
              <a href="page2/index.html">Go to Page 2</a>
          </body>
          </html>' > public/page3/index.html

      - name: Upload generated HTML files as artifact
        uses: actions/upload-artifact@v3
        with:
          name: html-pages
          path: public/

  deploy-pages:
    needs: generate-pages
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Download generated HTML pages artifact
        uses: actions/download-artifact@v3
        with:
          name: html-pages
          path: public/

      - name: Set up Git configuration for push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Commit and push changes to main branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add public/
          git diff --cached --exit-code || git commit -m "Deploy HTML pages to public folder"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} main --force

  display-summary:
    needs: deploy-pages
    runs-on: ubuntu-latest
    steps:
      - name: Display link to pages
        run: |
          echo "## HTML Pages Deployed to GitHub Pages" >> $GITHUB_STEP_SUMMARY
          echo "You can view the pages by clicking the links below:" >> $GITHUB_STEP_SUMMARY
          echo "Main page: [Preview Main Page](https://raw.githack.com/${{ github.repository }}/main/public/index.html)" >> $GITHUB_STEP_SUMMARY
          echo "Page 1: [Preview Page 1](https://raw.githack.com/${{ github.repository }}/main/public/page1/index.html)" >> $GITHUB_STEP_SUMMARY
          echo "Page 2: [Preview Page 2](https://raw.githack.com/${{ github.repository }}/main/public/page2/index.html)" >> $GITHUB_STEP_SUMMARY
          echo "Page 3: [Preview Page 3](https://raw.githack.com/${{ github.repository }}/main/public/page3/index.html)" >> $GITHUB_STEP_SUMMARY
