name: Generate HTML and Display in Summary

on:
  push:
    branches:
      - main

jobs:
  generate-html:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Generate HTML
        run: |
          mkdir -p public
          echo '<!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>GitHub Actions Example</title>
          </head>
          <body>
              <h1>Bem-vindo ao GitHub Actions!</h1>
              <p>Este é um exemplo de página estática gerada automaticamente e visível no summary.</p>
          </body>
          </html>' > public/index.html

      - name: Upload HTML as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: html-file
          path: public/

  display-summary:
    needs: generate-html
    runs-on: ubuntu-latest
    steps:
      - name: Display HTML in Summary
        run: |
          echo "## HTML File Generated" >> $GITHUB_STEP_SUMMARY
          echo "Click [here](https://github.com/${{ github.repository }}/suites/${{ github.run_id }}/artifacts) to download the HTML artifact" >> $GITHUB_STEP_SUMMARY
          echo "Or you can view the HTML file directly by following the link below:" >> $GITHUB_STEP_SUMMARY
          echo "![HTML preview](https://raw.githubusercontent.com/${{ github.repository }}/main/public/index.html)" >> $GITHUB_STEP_SUMMARY
