name: Publish HTML to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  generate-html:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Generate HTML
        run: |
          mkdir -p public
          echo '<!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>GitHub Pages Example</title>
          </head>
          <body>
              <h1>Bem-vindo ao GitHub Pages!</h1>
              <p>Este é um exemplo de página estática gerada automaticamente.</p>
          </body>
          </html>' > public/index.html

      - name: Upload HTML as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: html-file
          path: public/

  deploy-html:
    needs: generate-html
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Download HTML Artifact
        uses: actions/download-artifact@v3
        with:
          name: html-file
          path: ./public

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
