name: Generate HTML and Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  generate-html:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Generate HTML
        run: |
          mkdir -p public
          echo '<!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>GitHub Actions Example</title>
          </head>
          <body>
              <h1>Bem-vindo ao GitHub Actions!</h1>
              <p>Este é um exemplo de página estática gerada automaticamente.</p>
          </body>
          </html>' > public/index.html

  deploy-pages:
    needs: generate-html
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: public
          token: ${{ secrets.GITHUB_TOKEN }}  # Usa o token do GitHub para deploy
          
  display-summary:
    needs: deploy-pages
    runs-on: ubuntu-latest
    steps:
      - name: Display Link to Open HTML in Browser
        run: |
          echo "## HTML File Generated and Deployed to GitHub Pages" >> $GITHUB_STEP_SUMMARY
          echo "You can view the HTML file by clicking the link below:" >> $GITHUB_STEP_SUMMARY
          echo "Open [HTML file in browser](https://<USERNAME>.github.io/<REPOSITORY>/index.html)" >> $GITHUB_STEP_SUMMARY
