name: Generate HTML and Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  generate-html:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Generate HTML file
        run: |
          mkdir -p public
          echo '<!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>GitHub Actions Example</title>
          </head>
          <body>
              <h1>Bem-vindo ao GitHub Actions!</h1>
              <p>Este é um exemplo de página estática gerada automaticamente.</p>
          </body>
          </html>' > public/index.html

      - name: Upload HTML as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: html-artifact
          path: public/

  deploy-pages:
    needs: generate-html
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Download the generated HTML artifact
        uses: actions/download-artifact@v3
        with:
          name: html-artifact
          path: ./public

      - name: Deploy to GitHub Pages
        run: |
          # Set up git configuration
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Check out the gh-pages branch
          git checkout gh-pages || git checkout --orphan gh-pages

          # Copy the contents of the public directory to the root
          cp -R public/* .

          # Add, commit, and push the changes to gh-pages branch
          git add .
          git commit -m "Deploy HTML to GitHub Pages"
          git push origin gh-pages

  display-summary:
    needs: deploy-pages
    runs-on: ubuntu-latest
    steps:
      - name: Display Link to Open HTML in Browser
        run: |
          echo "## HTML File Generated and Deployed to GitHub Pages" >> $GITHUB_STEP_SUMMARY
          echo "You can view the HTML file by clicking the link below:" >> $GITHUB_STEP_SUMMARY
          echo "Open [HTML file in browser](https://<USERNAME>.github.io/<REPOSITORY>/index.html)" >> $GITHUB_STEP_SUMMARY
